### PR TITLE
Issue 10/implement packaging

### PR DESCRIPTION
**Pull request by itsmarcy**
Implement packaging for ngsi-pm scripts.

I was able to successfully build conda packages with these changes. ngsi_pm_py was only able to successfully build if the `--no-test` was passed. The tsv files under resources refer to an absolute path and the test when building do not pass because of this. Otherwise, everything works as expected.

### CODE REVIEW

**Review by walkerh — CHANGES_REQUESTED** [review]
1. The version in `meta.yaml` should be loaded from setup.py. See [this example](../../conda_demo_py/blob/d98abab61f3b8443a1c151cb21d50051a7475e49/conda.recipe/meta.yaml). The only place where the version should appear is in `ngsi_pm_py/version.py`.
2. You are using version `2.2.0rc1`, for which there is already a GitHub [release](../releases/tag/v2.2.0rc1). This is a _backwards-breaking_ change, and it has the testing problem below. I reject recycling `2.2.0rc1` and would propose the version `3.0.0b1`.
3. You should create an issue about the problem with testing.

**Comment by itsmarcy** [comment]
1. This is already happening in `meta.yaml` for `ngsi_pm_py`. I'm not sure if I am missing something or not understanding you.
2. Done.
3. I will once this PR is merged as the issue does not exist unless this is merged.

**Comment by walkerh** [comment]
1. My bad. I saw the wrong version of the `meta.yaml`.

Approving.

**Review by walkerh — APPROVED** [review]

**Comment by jekwatt** [comment]
Should we remove `__version__` from individual scripts?  I don't think they are properly updated.

eg
mplx_qc.py
`__version__ = '1.2.0'`

**Comment by walkerh** [comment]
@itsmarcy What do you think about that [question](#issuecomment-507720813)?

**Comment by walkerh** [comment]
@jekwatt Do you think your version [question](#issuecomment-507720813) should hold up this PR or be the subject for a possible new issue?

**Comment by itsmarcy** [comment]
Having them jump from `1.2.0` to `3.0.0b1` is weird but I rather have everything be the same `3.0.0b1` then be a different version especially now that is packaged.

**Comment by walkerh** [comment]
Well that answer's my question to @jekwatt too.

**Comment by jekwatt** [comment]
I concur with @itsmarcy.  I prefer to have everything be the same.

**Comment by itsmarcy** [comment]
Updated. Version is now consistent across all scripts.

**Pull request merged**
